### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by asadanas** [asadanas/Github-Crush-Course#1]
I think it would be better if the main title were a bit more orange.
The style rule could be changed like this:
```css
h1 {
  color: #e8d4b2;
}
```
