### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by learninggit06** [asadanas/Github-Crush-Course#3]
I think it looks better if the main title is a bit more orange.
The style rule could be change like this:
```css
h1 {
  color: #e8d4b2;
}
```
